#!/bin/bash

IMAGE_DIR="$HOME/Utils/images"
IMAGE="$IMAGE_DIR/android.img"

qemu-system-x86_64 \
  -bios /usr/share/qemu/bios.bin \
  -drive format=raw,file="$IMAGE" \
  -m 4096 -machine type=q35,accel=kvm -cpu max \
  -smp 8,sockets=1,cores=8,threads=1 \
  -device virtio-vga \
  -display sdl,gl=on -ctrl-grab \
  -nic user,model=e1000 \
  -device ich9-intel-hda -device hda-duplex \
  -usb -device usb-host,vendorid=0x30c9,productid=0x0013
