#!/bin/bash

rmmod i2c_hid
modprobe i2c_hid
yes | pacman -Scc
yes | pacman -R "$(pacman -Qtdq)"
yes | pamac remove -o
[ "$1" = --webcam ] && chmod 0666 /dev/bus/usb/003/002
rm -rf '/mnt/SDXC/System Volume Information/'
rm -rf '/mnt/Assign/System Volume Information/'
rm -rf '/mnt/Assign/$RECYCLE.BIN'
