#!/bin/sh

HELP="manjaro RAM_IN_MB"
IMAGE=~/Utils/images/manjaro.img
HOSTFWD=\
hostfwd=::50022-:22,`# SSH`\
hostfwd=::50080-:80`# HTTP`

if (( $# == 0 )); then
  echo "$HELP"
else
  prime-run qemu-system-x86_64 \
    -bios /usr/share/qemu/bios.bin \
    -drive format=raw,file=$IMAGE \
    -m $1 -machine type=q35,accel=kvm -cpu max \
    -smp 8,sockets=1,cores=8,threads=1 \
    -device virtio-vga,virgl=on \
    -display sdl -ctrl-grab \
    -nic user,model=e1000,$HOSTFWD \
    -device ich9-intel-hda -device hda-duplex \
    -usb -device usb-host,vendorid=0x30c9,productid=0x0013
fi
