#!/bin/bash

HELP="manjaro RAM_IN_MB"
IMAGE="$HOME/Utils/images/manjaro.img"

if (( $# == 0 )); then
  echo "$HELP"
else
  prime-run qemu-system-x86_64 \
    -bios /usr/share/qemu/bios.bin \
    -drive format=raw,file=$IMAGE \
    -m $1 -machine type=q35,accel=kvm -cpu max \
    -smp 8,sockets=1,cores=8,threads=1 \
    -device virtio-vga \
    -display sdl -ctrl-grab \
    -nic user,model=e1000,smb=/mnt/Volatile \
    -device ich9-intel-hda -device hda-duplex \
    -usb -device usb-host,vendorid=0x30c9,productid=0x0013
fi
