#!/bin/bash

MIDO_ADB_PORT=5555
MIDO_FTP_PORT=2221
MIDO_SESSION=~/Utils/rdb/mido.session
MIDO_MESSAGE="open --cast|--ftp"

function scan_open_ip {
  routed_ip=`ip route | awk '/default via/{ printf "%s/24", $3 }'`
  for i in {0..99}; do
    open_ip=`nmap -p $1 $routed_ip --open \
      --min-parallelism 100 | awk '/scan report/{ print $5 }'`
    if [ $open_ip ]; then
      echo $open_ip
      break
    fi
  done
}

function get_open_ip {
  if [ -f $MIDO_SESSION ]; then
    notify-send "Get Session..."
    open_ip=`cat $MIDO_SESSION`
    ip_stat=`true &>/dev/null \
      </dev/tcp/$open_ip/$1 && echo open || echo close`
    if [ $ip_stat == open ]; then
      echo $open_ip
      return
    fi
    notify-send "Session Expired"
  fi
  notify-send "Scanning..."
  open_ip=`scan_open_ip $1`
  echo $open_ip > $MIDO_SESSION
  echo $open_ip
}

function ip_with_port {
  open_ip=`get_open_ip $1`
  echo $open_ip:$1
}

if [ $# -eq 0 ]; then
  echo $MIDO_MESSAGE
else
  case $1 in
    --cast)
      open_ip=`ip_with_port $MIDO_ADB_PORT`
      adb connect $open_ip
      notify-send "Displaying..."
      scrcpy --max-size 1280 --max-fps 60 \
        --serial $open_ip --window-height 720 --window-width 405
      ;;
    --ftp)
      open_ip=`ip_with_port $MIDO_FTP_PORT`
      notify-send "Open..."
      exo-open --launch FileManager ftp://$open_ip
      ;;
    *)
      echo $MIDO_MESSAGE
      ;;
  esac
fi
