#!/bin/bash

ADB_PORT=5555
FTP_PORT=2221
DEFAULT_PERMS=0777
SESSION_DIR=~/Utils/rdb
SESSION="$SESSION_DIR/mido.session"
MAX_LOOP=99
HELP="open --cast|--ftp"

[ ! -d "$RDB_DIR" ] && mkdir -m $DEFAULT_PERMS -p "$SESSION_DIR"

scan_ip() { # ( ip )
  routed=$(ip route | awk '/default via/{ printf "%s/24", $3 }')
  for i in {0..$MAX_LOOP}; do
    ip=$(
      nmap -p "$1" "$routed" --open \
        --min-parallelism "$MAX_LOOP" | awk '/scan report/{ print $5 }')
    if [ -n "$ip" ]; then
      echo "$ip"
      break
    fi
  done
}

get_ip() { # ( port )
  if [ -f "$SESSION" ]; then
    notify-send "Get session..."
    ip=$(cat "$SESSION")
    if [ true &> /dev/null </dev/tcp/"$ip"/"$1" ]; then
      echo $ip
      return
    fi
    notify-send "Session expired..."
  fi
  notify-send "Scanning..."
  ip=$(scan_ip "$1")
  echo $ip > "$SESSION"
  echo $ip
}

if (( $# == 0 )); then
  echo $HELP
else
  case "$1" in
    --cast)
      ip=$(get_ip "$ADB_PORT")
      adb connect "$ip:$ADB_PORT"
      notify-send "Displaying..."
      scrcpy --max-size 1280 --max-fps 60 \
        --serial "$ip:$ADB_PORT" --window-height 720 --window-width 405
    ;;
    --ftp)
      ip=$(get_ip "$FTP_PORT")
      notify-send "Open..."
      exo-open --launch FileManager "ftp://$ip:$FTP_PORT"
    ;;
    *) echo $HELP;;
  esac
fi
