#!/bin/sh

EXIT_SUCCESS=0
EXIT_FAILURE=1
ITER=65536
HELP="\
Penggunaan: secret COMMAND [MESSAGE]...
Alat enkripsi dengan AES 256-bit CBC.

Commands:
  -e    enkripsi pesan.
  -d    deskripsi pesan.

Contoh:
  secret -e \"Hello World.\"
  secret -d \"U2FsdGVkX18T0XCDgEDxM7ht/M0XEwz3iyETstFKTBI=\""

hex_to_bin() {
  hex_formatted=$(printf "$1" | sed 's/../&\\x/g; s/^/\\x/; s/\\x$//')
  printf "$hex_formatted"
}

gen_encrypted_msg() {
  encrypted=$(printf "$1" | openssl aes-256-cbc -a -e -pbkdf2 -iter $ITER)
  clear
  echo "Pesan yang dienkripsi:"
  echo "$encrypted"
}

gen_decrypted_msg() {
  decrypted=$(printf "$1\n" | openssl aes-256-cbc -a -d -pbkdf2 -iter $ITER)
  clear
  echo "Pesan yang dideskripsi:"
  echo "$decrypted"
}

if (( $# <= 1 )); then
  echo "$HELP"
  exit $EXIT_FAILURE
else
  case "$1" in
    -e)
      gen_encrypted_msg "$2"
      exit $EXIT_SUCCESS
    ;;
    -d)
      gen_decrypted_msg "$2"
      exit $EXIT_SUCCESS
    ;;
    *)
      echo "$HELP"
      exit $EXIT_FAILURE
    ;;
  esac
fi
