#!/bin/sh

HELP="xmanjaro RAM_IN_MB"
BASE=~/Utils/images/manjaro.img
VOLATILE_DIR=/mnt/Volatile
IMAGE="$VOLATILE_DIR/manjaro.img"
HOSTFWD=\
hostfwd=::10022-:2200,`# SSH`\
hostfwd=::10080-:8000,`# HTTP`\
hostfwd=::13306-:3306,`# MariaDB`\
hostfwd=::18080-:8080`# PhpMyAdmin`

if (( $# == 0 )); then
  echo "$HELP"
else
  [ ! -f "$IMAGE" ] && cp --sparse=always "$BASE" "$IMAGE"
  prime-run qemu-system-x86_64 \
    -bios /usr/share/qemu/bios.bin \
    -drive format=raw,file="$IMAGE" \
    -m $1 -machine type=q35,accel=kvm -cpu max \
    -smp 8,sockets=1,cores=8,threads=1 \
    -device virtio-vga,virgl=on,xres=1440,yres=900 \
    -display sdl -ctrl-grab \
    -nic user,model=e1000,smb=/mnt/Volatile,"$HOSTFWD" \
    -device ich9-intel-hda -device hda-duplex \
    -usb -device usb-host,vendorid=0x30c9,productid=0x0013
fi
