#!/bin/bash

MESSAGE="xmanjaro RAM_IN_MB"
IMAGE=/mnt/Volatile/manjaro.img
HOSTFWD=\
hostfwd=::50022-:22,`# SSH`\
hostfwd=::50122-:50122,`# Docker SSH`\
hostfwd=::50136-:50136,`# Docker MariaDB`\
hostfwd=::50180-:50180,`# Docker Apache`\
hostfwd=::50188-:50188`# Docker MyAdmin`

if [ $# -eq 0 ]; then
  echo $MESSAGE
else
  prime-run qemu-system-x86_64 \
    -bios /usr/share/qemu/bios.bin \
    -drive format=raw,file=$IMAGE \
    -m $1 -machine type=q35,accel=kvm -cpu max \
    -smp 8,sockets=1,cores=8,threads=1 \
    -device virtio-vga,virgl=on \
    -display sdl -ctrl-grab \
    -nic user,model=e1000,$HOSTFWD \
    -device ich9-intel-hda -device hda-duplex \
    -usb -device usb-host,vendorid=0x30c9,productid=0x0013
fi
