#!/usr/bin/env bash

SYSTEM=$(uname -s)
case "$SYSTEM" in
  Linux*)
    gcc \
      -I. -Ofast -march=native \
      shell.c sqlite3.c -o sqlite3
  ;;
  MINGW* | CYGWIN*)
    ./compile.bat
  ;;
  *)
    echo 'Cannot compile, unknown system.'
  ;;
esac
